name: nfc_phone_pay
description: NFC Tap-to-Pay with external payment links and hacker style
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.6.0
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  sqflite: ^2.3.0
  path: ^1.8.0
  path_provider: ^2.0.11
  url_launcher: ^6.2.6
  credit_card_validator: ^2.0.0
  animated_text_kit: ^4.2.2
  qr_flutter: ^4.1.0
  #qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.5.0      # (or the latest version)
  flutter_blue_plus: ^1.35.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/FiraMono-Regular.ttf
    - assets/images/logo.png
  fonts:
    - family: FiraMono
      fonts:
        - asset: assets/fonts/FiraMono-Regular.ttf